#!/bin/bash

#SBATCH --job-name=fastqc
#SBATCH --output="slurm-%j.out"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=40G
#SBATCH --time=9:00:00
#SBATCH --partition=pi_gerstein
#SBATCH --mail-type=FAIL

module load FastQC/0.11.9-Java-11

fastqc -R.fastq.gz  -R2.fastq.gz  -o fastqc --extract -f fastq
